name: divisioniosfinal
description: A new Flutter project.

publish_to: 'none'

version: 1.0.4

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_screenutil:
  get:
  http:
  flutter_svg:
  fluttertoast:
  flutter_staggered_grid_view: ^0.4.0
  connectivity_plus:
  shared_preferences:
  flutter_html:
  image_picker:
  image_cropper:
  dio:
  cached_network_image:
  intl:
  url_launcher:
  lottie:
  excel:
  open_filex:
  path_provider:
  path:
  pdf:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications: ^9.7.0
  flutter_spinkit:
  loading_progress:
  permission_handler:
  flutter_pdfview:
  flutter_inappwebview:
  rxdart:
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/dlogo.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/GothamMedium.ttf
          weight: 500
    - family: Fake Receipt
      fonts:
        - asset: assets/fonts/fake_receipt.ttf
          weight: 400
    - family: HydrogenType
      fonts:
        - asset: assets/fonts/hydrogen.ttf
          weight: 400
    - family: DIN Next LT Arabic Light
      fonts:
        - asset: assets/fonts/DIN Next LT Arabic Light.ttf

